// <auto-generated />
namespace StudentManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TeacherApplication1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeacherApplication1));
        
        string IMigrationMetadata.Id
        {
            get { return "201707071644548_TeacherApplication1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
